### ISSUE TITLE
Set up redirects for old regional URLs

### ISSUE THREAD

**Issue by shawnbot** [18F/doi-extractives-data#1326]
When we implement regional pages (as sketched in #1267) we'll need to:

- [x] look at the analytics to see if anyone is actually linking to the regional explore data views, so that we can decide whether to...
- [x] set up redirects for the old URLs that send visitors to the new ones

One way to do this could be to put together some redirect logic for different URLs in the form of [URI templates](https://tools.ietf.org/html/rfc6570) that could live in the front matter of each page, as in:

```yaml
redirects:
  region: {region}/{?year}
  region,commodity: {region}/{?year}#{commodity}
  region,commodity,product: {region}/{?year}#{commodity}/{product}
```

So the JavaScript for that page would check (from the longest to the shortest) whether the hash contained all of those parameters, and for the first one it finds, redirect to the corresponding URL.
