### ISSUE TITLE
Use a different Google Analytics tracking ID on Federalist

### ISSUE THREAD

**Issue by shawnbot** [18F/doi-extractives-data#1343]
Right now we've got a bunch of Federalist URLs mixed in with those of the production site, and while it's not skewing the numbers because the paths are different, it does make it harder to skim lists of paths and get a sense for popular landing pages. The ideal solution is to use a different GA tracking ID on Federalist than we do on the production site. We can do this by putting tracking ID into `_config.yml`, pulling it out of [the JavaScript](https://github.com/18F/doi-extractives-data/blob/294a5457e399dd4dc62c570cf78cfb564958d410/js/src/main.js#L46) (it should probably be inlined at the bottom of the default layout), then setting up our Federalist config like so:

```yaml
google_analytics:
  # XXX here is our Federalist tracking ID
  default: 'XXX'
  # only use this tracking ID on master (production)
  master: 'UA-48605964-8'
```

and in our template we would use:

```
{{ google_analytics[site.branch]|default:google_analytics.default }}
```

This works because `site.branch` gets set by Federalist at build time, so when `site.branch == 'master'` the output value would be the production tracking ID; otherwise `XXX`. And if we _only_ put the `google_analytics` setting in the Federalist config (as opposed to hard-coding it in `_config.yml`) then we can further refine the page template to just skip the GA bit altogether and not do any analytics when it's running locally.
