### ISSUE TITLE
Make Circle CI config for dev branch

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1566]
## Expected Behavior
That Circle CI throws an error when tests fail and does not throw an error when tests pass

## Actual Behavior
On `dev` Circle is throwing the following error because we don't have a `circle.yml` file for the Circle build to take instructions from.
```
Gem::InstallError: jekyll requires Ruby version >= 2.0.0.
Installing nokogiri 1.6.7.1
An error occurred while installing jekyll (3.0.0.pre.beta9), and Bundler cannot
continue.
Make sure that `gem install jekyll -v '3.0.0.pre.beta9'` succeeds before
bundling.
```

## Steps to reproduce the behavior
Add a `circle.yml` config file that looks like:

```
## Customize the test machine
machine:
  # Version of ruby to use
  ruby:
    version:
      2.2.3

## Customize dependencies
dependencies:
  pre:
    - gem install jekyll -v '3.0.0.pre.beta9'
    - bundle install
    - bundle exec jekyll build

## Customize test commands
test:
  pre:
    # - npm run test-html
    - npm run test
```
