### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2256]
- [ ] http://quickfacts.census.gov/qfd/states/02/02185.html
- [ ] http://www.lbb.state.tx.us/Other_Pubs/Natural%20Gas%20Tax%20Overview.pdf
- [ ] http://finance.utah.gov/reporting/documents/11FinalFinancialHighlightsNovemberIssue.pdf;
- [ ] http://www.blm.gov/wo/st/en.html
- [ ] http://www.glo.texas.gov/what-we-do/energy-and-minerals/oil_gas/
- [ ] http://www.blm.gov/mt/st/en/prog/energy/oil_and_gas/leasing.html
- [ ] http://www.revenue.state.mn.us/businesses/mineral/Documents/2013_mining_guide.pdf
- [ ] http://www.leginfo.ca.gov/cgi-bin/displaycode?section=prc&group=06001-07000&file=6826-6836
- [ ] http://mn.gov/irrrb/images/2013-2014%2520Biennial%2520Report.pdf
- [ ] http://www.bsee.gov/uploadedFiles/BSEE/Regulations_and_Guidance/Notices_to_Lessees/2012/NTL2012-N03.pdf
- [ ] http://www.dot.state.mn.us/measures/pdf/2012ReportBook4-15.pdf
- [ ] http://labor.alaska.gov/research/reshire/NONRES.pdf
- [ ] https://wwwprd.doa.louisiana.gov/opb/pub/FY02/22-non/22-917.pdf
- [ ] https://wwwprd.doa.louisiana.gov/opb/pub/FY02/22-non/22-918.pdf
- [ ] http://www.nps.gov/history/hpg/
- [ ] http://www.blm.gov/wo/st/en/prog/energy/solar_energy.html
- [ ] http://www.blm.gov/wy/st/en/programs/energy/Coal_Resources/PRB_Coal.html
- [ ] http://www.blm.gov/wo/st/en/prog/energy.html
- [ ] http://www.blm.gov/pgdata/etc/medialib/blm/wo/Communications_Directorate/legislation.Par.23212.File.dat/mla_1920_amendments1.pdf
- [ ] http://www.blm.gov/wo/st/en/prog/energy/oil_and_gas.html
- [ ] http://www.glo.texas.gov/what-we-do/state-lands/permanent-school-fund/index.html
- [ ] http://www.census.gov/compendia/statab/cats/energy_utilities.html
- [x] https://eiti-dev.18f.gov/communities
- [x] https://useiti.doi.gov/data/
- [ ] http://www.blm.gov/pgdata/etc/medialib/blm/wo/Communications_Directorate/legislation.Par.23212.File.dat/mla_1920_amendments1.pdf#page=56
- [ ] http://www.dhsem.wv.gov/Resources/Documents/WV%20Emergency%20Operations%20Plan.pdf
- [ ] http://www.blm.gov/wo/st/en/prog/planning/nepa/field_office_nepa.html
- [ ] http://www.blm.gov/flpma/FLPMA.pdf
- [ ] http://www.blm.gov/wo/st/en/prog/energy/oil_and_gas/best_management_practices/gold_book.html
- [ ] http://www.blm.gov/wo/st/en/prog/energy/oil_and_gas/leasing_of_onshore.html
- [ ] http://www.blm.gov/wo/st/en/prog/energy/coal_and_non-energy.html
- [ ] https://eiti.org/files/English_EITI_STANDARD.pdf
- [ ] http://www.blm.gov/wo/st/en/prog/energy/oil_and_gas/questions_and_answers.html
- [ ] http://mn.gov/irrrb/images/2014%2520Explore%2520IRON%2520ORE.pdf
- [ ] http://www.blm.gov/pgdata/content/wo/en/prog/planning/planning_overview/eplanning2.html
- [ ] http://www.oge.gov/Financial-Disclosure/Financial-Disclosure/
- [ ] http://www.blm.gov/co/st/en/BLM_Programs/minerals/Coal.html#Coal_Exploration_Licenses
- [ ] http://www.treasury.gov/resource-center/tax-policy/Documents/Tax-Expenditures-FY2017-Revised.pdf
- [ ] http://www.blm.gov/wo/st/en/prog/energy/oil_and_gas/best_management_practices/split_estate.html

**Comment by gemfarmer** [comment]
cc @meiqimichelle @mentastc

**Comment by gemfarmer** [comment]
I ran a script to check all of these links and see where they have moved to, and all eventually led to 404s. The info may be elsewhere, but the system administrator who moved the links didn't make it easy to track where...

**Comment by mentastc** [comment]
I updated the file that has the links for the web. let me know if you only want the broken ones. 
[useiti-search 05.01.17.docx](https://github.com/18F/doi-extractives-data/files/970792/useiti-search.05.01.17.docx)

**Comment by mentastc** [comment]
@gemfarmer @meiqimichelle

**Comment by gemfarmer** [comment]
This is great @mentastc! I'll take a look at these links :)

**Comment by gemfarmer** [comment]
@mentastc for the ones that say cannot find, should I remove them?

**Comment by coreycaitlin** [comment]
@gemfarmer mind waiting on me to take a look, just for situational awareness?

**Comment by gemfarmer** [comment]
@mentastc I made some updates and these are the links that are still broken:

```
- title: U.S. Census Bureau Energy and Utilities Statistics
  url: https://www.census.gov/library/publications/2011/compendia/statab/131ed/energy-utilities.html
  description: "Statistics on fuel resources, energy production and consumption, electric energy, hydroelectric power, nuclear power, solar energy, wood energy, and the electric and gas utility industries."
  tag:
  - energy
  - utilities
  - statistics
  - Census

- title: Bureau of Land Management National Environmental Policy Act
  url: http://www.blm.gov/pgdata/content/wo/en/prog/planning/planning_overview/eplanning2.html
  description: "BLM’s ePlanning brings the Land Use Planning (LUP) as well as the National Environmental Policy Act (NEPA) process into your home or local library. With an Internet-connected computer, you can open and read land use planning and NEPA documents produced with ePlanning. You can search for issues such as recreation, wildlife, or energy. During the comment periods, you can easily submit your comments online! With ePlanning's comment features, you can tie your comment to particular text right out of the land use planning or NEPA document."
  tag:
  - NEPA
  - EIS
  - environmental
  - land
  - use
  - planning
  - development
  - BLM

- title: BLM-Mineral Leasing Act of 1920
  url: https://www.blm.gov/pgdata/etc/medialib/blm/wo/Communications_Directorate/legislation.Par.23212.File.dat/mla_1920_amendments1.pdf
  description: "Mineral Leasing Act of 1920 as Amended- Creates a system of leasing mineral resources on federal lands for extraction and grants BLM authority to administer mineral leasing."
  tag:
  - Mineral
  - Leasing
  - Act
  - 1920
  - BLM

- title: "BLM, BLM Colorado Coal: Coal Exploration Licenses"
  url: http://www.blm.gov/co/st/en/BLM_Programs/minerals/Coal.html#Coal_Exploration_Licenses
  description: "Most of the coal reserves in Colorado are subbituminous (lowest sulfur content and cleanest burning coal), which are used for generating electricity. In Colorado, there are currently seven producing coal mines (six underground and two surface) encompassing 60,000 acres. In Fiscal Year 2014, coal energy production on BLM Colorado public lands directly contributed $721 million to the economy, generating royalty revenue of $42 million and accounted for 5,144 direct and indirect jobs in Colorado."
  tag:
  - Coal
  - Colorado
  - BLM
  - Leasing
  - Royalty

- title: The Louisiana Division of Administration, Program 22-917
  url: https://wwwprd.doa.louisiana.gov/opb/pub/FY02/22-non/22-917.pdf
  description: "The Louisiana Division of Administration, Program 22-917, Severance Tax Dedication"
  tag:
  - Severance
  - Tax
  - LA

- title: The Louisiana Division of Administration, Program 22-918
  url: https://wwwprd.doa.louisiana.gov/opb/pub/FY02/22-non/22-918.pdf
  description: "The Louisiana Division of Administration, Program 22-918, Parish Royalty Fund"
  tag:
  - LA
  - Royalty
  - Fund

- title: Federal Financial Management Improvement Act of 1996 (FFMIA)
  url: http://www.thefreelibrary.com/The+Federal+Budget%3a+Politics%2c+Policy%2c+Process.-a074830086
  description: "FFMIA requires federal agencies to implement and maintain financial management systems that substantially comply with federal financial management systems requirements, applicable federal accounting standards, and the US Standard General Ledger at the transactional level."
  tag:
  - FFMIA
  - Financial
  - Management
  - Improvement

- title: The Office of Management and Budget, OMB Circular 123
  url: https://obamawhitehouse.archives.gov/omb/circulars_a123_rev
  description: "OMB Circular No. A-123 defines management's responsibility for internal control in Federal agencies. A re-examination of the existing internal control requirements for Federal agencies was initiated in light of the new internal control requirements for publicly-traded companies contained in the Sarbanes-Oxley Act of 2002. Circular A-123 and the statute it implements, the Federal Managers’ Financial Integrity Act of 1982, are at the center of the existing Federal requirements to improve internal control"
  tag:
  - OMB
  - A-123
```
