### ISSUE TITLE
Make sticky side navs scrollable in short screens

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2306]
## Expected Behavior
When the screen height is small, you should be able to scroll to see hidden text

## Actual Behavior
This is not the case for the sticky sidenav text. 

## Steps to reproduce the behavior
It could be fixed by adding a class like the following to `.sticky_nav` element:
```css
.sticky-scrollable {
  max-height: 100vh;
  position: sticky;
  overflow: auto;
}
```
