### ISSUE TITLE
Disbursements lacks subnav items

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2589]
@ericronne noticed that (for example) [Production](https://revenuedata.doi.gov/explore/#production) has subnav items mapped to subheadings, but [Disbursements](https://revenuedata.doi.gov/explore/#federal-disbursements) does not.

I assume these are manually declared in the [explore/index.html](https://github.com/18F/doi-extractives-data/blob/0276aa1a1069ffe6e54c997c97aef4503ece3b07/explore/index.html) front matter.

```
  - name: production
    title: Production
    subnav_items:
      - name: all-production
        title: Nationwide
      - name: federal-production
        title: Federal lands and waters
```

```  
  - name: federal-disbursements
    title: Disbursements
```
