### ISSUE TITLE
Add sticky subnav to long navigation pages

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#995]
Nav should be applied to long law and governance narrative pages.
`how-it-works/state-legal-fiscal-info.md` is a good template. 

the following jekyll frontmatter:
```
nav_description: Jump to a state
nav_items:
  - name: ak
    title: Alaska
```

with corresponding markup: 
```
<h3><a name="ak" data-nav-header="ak">Alaska</a></h3>
```

Issue is complete when:
* [x] nav added to Laws and Governance Pages
* [x] nav added to Natural Resource pages
* [ ] nav added to any additional pages
* [ ] mobile version of nav added to all of the above
